---
version: '3'
services:
  zookeeper_matchprofile:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper
    container_name: zookeeper_matchprofile
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker_matchprofile:
    image: confluentinc/cp-kafka:5.5.0
    hostname: broker
    container_name: broker_matchprofile
    depends_on:
      - zookeeper_matchprofile
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  postgres_matchprofile:
    hostname: postgres
    container_name: postgres_matchprofile
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./src/test/resources/postgres:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=none"]

  matchprofile:
    build: .
    depends_on:
      - postgres_matchprofile
    ports:
      - "9090:8080"
    environment:
      DB_PASSWORD: matchprofile
      DB_USERNAME: matchprofile
      DB_DRIVER: org.postgresql.Driver
      DB_HOST: 'postgres'
      KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  opensearch_matchprofile:
    image: opensearchproject/opensearch:1.3.1
    container_name: opensearch_matchprofile
    environment:
      - node.name=opensearch_matchprofile
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9600:9600"
    profiles:
      - index

  opensearch_dashboards_matchprofile:
    image: opensearchproject/opensearch-dashboards:1.3.0
    container_name: opensearch_dashboards_matchprofile
    depends_on:
      - opensearch_matchprofile
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch_matchprofile:9200"]'
    profiles:
      - index

  matchprofile_index:
    image: ghcr.io/navikt/pam-matchprofile-index:22.110.112333
    depends_on:
      - zookeeper_matchprofile
      - opensearch_matchprofile
    ports:
      - "9091:8081"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'
    profiles:
      - index
